# Generated by Django 2.0.1 on 2018-01-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('private', 'Private')], default='draft', max_length=10),
        ),
    ]
