# Generated by Django 2.0.1 on 2018-02-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20180205_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='project_color',
            new_name='todo_priority',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='project_title',
        ),
    ]
