# Generated by Django 2.0.1 on 2018-02-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20180205_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_todo',
            field=models.DateField(),
        ),
    ]
