# Generated by Django 2.0.1 on 2018-02-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20180205_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_priority',
            field=models.CharField(max_length=250),
        ),
    ]
