# Generated by Django 2.0.1 on 2018-02-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20180205_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_priority',
            field=models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='high', max_length=250),
        ),
    ]
