# Generated by Django 2.0.1 on 2018-02-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20180205_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='album_logo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
