# Generated by Django 2.0.1 on 2018-02-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_todo_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_tasks',
            field=models.BooleanField(default=False),
        ),
    ]
